global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'flaskapp'
    static_configs:
      - targets: ['localhost:5000']
  - job_name: 'mariadb'
    static_configs:
      - targets: ['localhost:3306']
